name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name (e.g. v1.0.0)'
        required: false
        type: string
        default: ''
      release_title:
        description: 'Release Title (optional)'
        required: false
        type: string
      release_body:
        description: 'Release Description (one-line only) (optional)'
        required: false
        type: string
      create_release:
        description: 'Create GitHub Release'
        required: true
        type: boolean
        default: false
      auto_release_note:
        description: 'Generate release note'
        required: true
        type: boolean
        default: false

env:
  BIN_NAME: quantum_launcher
  PROJECT_NAME: quantum_launcher
  CARGO_TERM_COLOR: always # Tell cargo to always use colors

jobs:
  dist:
    name: Dist
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # don't fail other jobs if one fails
      matrix:
        build:
          [
            x86_64-linux,
            aarch64-linux,
            armv7-linux,
            x86_64-macos,
            x86_64-windows,
            aarch64-macos,
            aarch64-windows,
            i686-windows,
          ]
        include:
          - build: x86_64-linux
            os: ubuntu-22.04
            rust: stable
            target: x86_64-unknown-linux-gnu
            cross: false
            final_name: linux_x86_64
          - build: aarch64-linux
            os: ubuntu-22.04-arm
            rust: stable
            target: aarch64-unknown-linux-gnu
            cross: false
            final_name: linux_aarch64
          - build: armv7-linux
            os: ubuntu-22.04
            rust: stable
            target: armv7-unknown-linux-gnueabihf
            cross: true
            final_name: linux_arm32
          - build: x86_64-macos
            os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
            cross: false
            final_name: macos_x86_64
          - build: x86_64-windows
            os: windows-latest
            rust: stable
            target: x86_64-pc-windows-msvc
            cross: false
            final_name: windows_x86_64
          - build: aarch64-macos
            os: macos-latest
            rust: stable
            target: aarch64-apple-darwin
            cross: false
            final_name: macos_aarch64
          - build: aarch64-windows
            os: windows-11-arm
            rust: stable
            target: aarch64-pc-windows-msvc
            cross: false
            final_name: windows_aarch64
          - build: i686-windows
            os: windows-latest
            rust: stable-i686
            target: i686-pc-windows-msvc
            cross: false
            final_name: windows_i686

    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install dependencies
        if: matrix.os == 'ubuntu-22.04' || matrix.os == 'ubuntu-22.04-arm'
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev pkg-config libdbus-1-3

      # Unblock when nasm is a requirement
      # - uses: ilammy/setup-nasm@v1

      - name: Install rustup for ${{ matrix.os }}
        if: matrix.os == 'windows-11-arm'
        shell: bash
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://win.rustup.rs/aarch64 -o rustup-init.exe
          ./rustup-init.exe -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install ${{ matrix.rust }} toolchain
        shell: bash
        run: |
          rustup toolchain install ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
          rustup target add ${{ matrix.target }}
          if [ "${{ matrix.cross }}" == "true" ]; then
            cargo install cross --locked
          fi

      - name: Build release binary
        shell: bash
        run: |
          if [ "${{ matrix.cross }}" == "true" ]; then
            cross build --profile release-ql --target ${{ matrix.target }}
          else
            cargo build --profile release-ql --target ${{ matrix.target }}
          fi

      - name: Build archive
        shell: bash
        run: |
          mkdir dist

          if [ "${{ matrix.build }}" = "x86_64-windows" ] || [ "${{ matrix.build }}" = "i686-windows" ]; then
            cp "target/${{ matrix.target }}/release-ql/${{ env.BIN_NAME }}.exe" "dist/"
          elif [ "${{ matrix.build }}" = "aarch64-macos" ] || [ "${{ matrix.build }}" = "x86_64-macos" ]; then
            APP_DIR="build/quantum-launcher.app"
            MACOS_DIR="$APP_DIR/Contents/MacOS"
            RESOURCES_DIR="$APP_DIR/Contents/Resources"
            mkdir -p "$MACOS_DIR" "$RESOURCES_DIR"
            cp "target/${{ matrix.target }}/release-ql/${{ env.BIN_NAME }}" "$MACOS_DIR/${{ env.BIN_NAME }}"
            cp assets/freedesktop/Info.plist "$APP_DIR/Contents/Info.plist"
            sips -s format icns "assets/icon/ql_logo.png" --out "$RESOURCES_DIR/ql_logo.icns"
            hdiutil create -volname "${{ env.BIN_NAME}}" -srcfolder "$APP_DIR" -ov -format UDZO "dist/${{ env.BIN_NAME }}.dmg"
          else
            cp "target/${{ matrix.target }}/release-ql/${{ env.BIN_NAME }}" "dist/"
          fi

      - uses: actions/upload-artifact@v5
        with:
          name: quantum-launcher-${{ matrix.final_name }}
          path: dist

  build-appimages:
    uses: ./.github/workflows/build-appimage.yml

  publish:
    name: Publish
    needs: [dist, build-appimages]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v6
      # - run: ls -alR

      - name: Determine Release Metadata
        id: meta
        env:
          MANUAL_BODY: ${{ github.event.inputs.release_body }}
        run: |
          set -xe
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ ${{ github.event.inputs.tag_name }} != "" ]; then
            echo "tag=${{ github.event.inputs.tag_name }}" >> $GITHUB_OUTPUT
            echo "title=${{ github.event.inputs.release_title || github.event.inputs.tag_name }}" >> $GITHUB_OUTPUT
            echo "enabled=${{ github.event.inputs.create_release }}" >> $GITHUB_OUTPUT

            # echo "body<<EOF" >> $GITHUB_OUTPUT
            # echo "$MANUAL_BODY" >> $GITHUB_OUTPUT
            # echo "EOF" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "push" ]
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT
            echo "title=$TAG_NAME" >> $GITHUB_OUTPUT
            echo "enabled=true" >> $GITHUB_OUTPUT
          fi

      - name: Build archive and Copy binaries
        shell: bash
        run: |
          set -xe
          mkdir -p dist
          for dir in quantum-launcher-* ; do
              binary_path=$(find "$dir" -type f | head -n 1)
              platform_name=$(basename "$dir" | sed 's/quantum-launcher-//')
              pkgname="${{ env.PROJECT_NAME }}_${platform_name}"
              zip -j "dist/$pkgname.zip" "$binary_path"
          done

      - name: Create Release and Upload Assets
        if: steps.meta.outputs.enabled == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          name: ${{ steps.meta.outputs.title }}
          files: dist/*
          generate_release_notes: ${{ github.event.inputs.auto_release_note }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload as artifact
        uses: actions/upload-artifact@v5
        with:
          name: artifacts
          path: dist/*

      - name: Trigger Flatpak Update
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        if: steps.meta.outputs.enabled == 'true' && env.GITHUB_TOKEN != ''
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository_owner }}/ql-flatpak-remote
          event-type: trigger-flatpak-update
          client-payload: '{"tag": "${{ steps.meta.outputs.tag }}"}'
